Website QlySpa/QlySpa/QlySpa/Areas/Admin/Controllers/ServiceTypeController.cs
using QlySpa.Models.DAO;
using QlySpa.Models.EF;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QlySpa.Areas.Admin.Controllers
{
    public class ServiceTypeController : Controller
    {
        // GET: Admin/ServiceType
        // GET: ServiceType
        public ActionResult Index(string NgayTH = "", int pageNum = 1, int pageSize = 8)
        {
            ViewBag.HienThi = "0";
            if (NgayTH != "")
            {
                ViewBag.HienThi = "1";
            }
            ViewBag.NgayTH = NgayTH;

            ServiceTypeDAO dao = new ServiceTypeDAO();
            if (!string.IsNullOrEmpty(NgayTH))
            {
                return View(dao.listLoaiDVByNgayTH(NgayTH, pageNum, pageSize));
            }

            return View(dao.lstjoin(pageNum, pageSize));
        }
        // create
        //[Authorize(Roles = "ADMIN")]
        public ActionResult Create()
        {
            ServiceTypeDAO dao = new ServiceTypeDAO();
            //QCDAO d = new QCDAO();
            //ViewBag.cat = dao.ListQC();
            return View();
        }
        [HttpPost]
        //[Authorize(Roles = "ADMIN")]
        public ActionResult Create(LoaiDichVu sp, HttpPostedFileBase photo)
        {
            var img = Path.GetFileName(photo.FileName);
            LoaiDichVu ServiceType = new LoaiDichVu();
            ServiceType.tenLoaiDV = sp.tenLoaiDV;
            ServiceType.NgayTao= DateTime.Now;
            ServiceType.NgayCapNhat = DateTime.Now;
            ServiceType.Gia = sp.Gia;
            ServiceType.NgayTH = sp.NgayTH;
            // them san pham vao db
            if (ModelState.IsValid)
            {
                if (photo != null && photo.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Areas/Admin/Content/images/"),
                                            System.IO.Path.GetFileName(photo.FileName));
                    photo.SaveAs(path);

                    ServiceType.Anh = photo.FileName;
                    ServiceTypeDAO dao = new ServiceTypeDAO();
                    dao.Create(ServiceType);
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View(ServiceType);
            }
        }

        //[Authorize(Roles = "ADMIN")]
        public ActionResult Edit(int id)
        {
            List<LoaiDichVu> ls = new List<LoaiDichVu>();
            ServiceTypeDAO dao = new ServiceTypeDAO();
            //QCDAO d = new QCDAO();
            //ViewBag.cat = d.ListQC();
            LoaiDichVu sp = dao.FindProductByID(id);
            ViewBag.id = id;
            //ViewBag.NgayTH = "";
            //if (sp.NgayTH != null)
            //{
            //    var lstDate = sp.NgayTH.ToString().Split(' ');
            //    var strDate = lstDate[0];
            //    //String dt = DateTime.ParseExact(strDate, "dd/MM/yyyy", CultureInfo.InvariantCulture).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture); ;
            //    //ViewBag.NgayDangKy = dt;
            //}

            //ViewBag.HanSuDung = "";
            //if (sp.HanSuDung != null)
            //{
            //    var lstDate = sp.HanSuDung.ToString().Split(' ');
            //    var strDate = lstDate[0];
            //    String dt = DateTime.ParseExact(strDate, "dd/MM/yyyy", CultureInfo.InvariantCulture).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture); ;
            //    ViewBag.HanSuDung = dt;
            //}

            return View(sp);
        }

        [HttpPost]

        public ActionResult Edit(LoaiDichVu sp, int id, HttpPostedFileBase photo)
        {
            ServiceTypeDAO dao = new ServiceTypeDAO();
            LoaiDichVu ServiceType = dao.FindProductByID(id);
            ServiceType.tenLoaiDV = sp.tenLoaiDV;
            ServiceType.NgayTH = sp.NgayTH;
            ServiceType.Gia = sp.Gia;
            ServiceType.NgayTao = (sp.NgayTao);
            ServiceType.NgayCapNhat = DateTime.Now;
            if (ModelState.IsValid)
            {
                if (photo != null && photo.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Areas/Admin/Content/images/"),
                                            System.IO.Path.GetFileName(photo.FileName));
                    photo.SaveAs(path);

                    ServiceType.Anh = photo.FileName;

                }
                ServiceTypeDAO d = new ServiceTypeDAO();
                d.Edit(ServiceType);
                return RedirectToAction("Index");
            }
            else
            {
                return View(ServiceType);
            }
        }

        // delete
        [HttpPost]
        //[Authorize(Roles = "ADMIN")]
        public string Delete(int id)
        {
            ServiceTypeDAO dao = new ServiceTypeDAO();
            LoaiDichVu sp = new LoaiDichVu();
            sp = dao.FindProductByID(id);
            if (sp != null)
            {
                dao.Delete(id);
            }
            return "OK";
        }
        public ActionResult Details(int id)
        {

            ServiceTypeDAO dao = new ServiceTypeDAO();
            LoaiDichVu sp = dao.FindProductByID(id);

            return View(sp);
        }
    }
}

Website QlySpa/QlySpa/QlySpa/Areas/Admin/Views/ServiceType/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model QlySpa.Models.EF.LoaiDichVu



@*@using (Html.BeginForm())
    {*@


<form action="Create" method="post" role="form" enctype="multipart/form-data">

    @Html.AntiForgeryToken()
    @*<form action="Create" method="post" role="form" enctype="multipart/form-data">

        @Html.AntiForgeryToken()*@

    @*<div class="form-horizontal">*@
    <div class="sec sec__shopcart">
        <div class="container">
            <div class="sec__shopcart__info col-md-12 col-xs-12 col-sm-12">
                <div class="box-user__info panel">
                    <h2><u>Thêm thông tin sản phẩm</u></h2>
                    <div class="content">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col-md-6 col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <div class="label">Tên sản phẩm</div>
                                    @Html.EditorFor(model => model.tenLoaiDV, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.tenLoaiDV, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6 col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <label class="control-label col-md-6" for="exampleInputFile">Hình ảnh</label>
                                    <div class="col-md-10">
                                        <input type="file" id="photo" name="photo">
                                        @*<p class="help-block">Chọn ảnh của sản phẩm</p>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <div class="label"> Số ngày thực hiện</div>
                                    @Html.EditorFor(model => model.NgayTH, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NgayTH, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6 col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <div class="lable">Giá</div>
                                    @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-2">
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-2">
                                <a href="@Url.Action("Index", "ServiceType") " class="btn btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@*}*@
<style>
    body {
    }

    h2 {
        color: royalblue;
        font-family: Arial;
        font-weight: bold;
    }
</style>

Website QlySpa/QlySpa/QlySpa/Areas/Admin/Views/ServiceType/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model QlySpa.Models.EF.LoaiDichVu

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 col-right">
            <!---->
            <div class="box-category">
                <div class="ct-detail-pr">
                    <div class="row ct-detail-top">
                        <div class="product__view__image col-md-6 col-sm-6 col-xs-12">
                            <div class="row">
                                <div class="col-sm-9 col-xs-12">
                                    <div class="product__view__image--list">
                                        <a href="#" data-fancybox="gallery" class="fancybox">
                                            <img src="/Areas/Admin/Content/images/@Model.Anh" style="width: 410px; height: 410px;" alt="name your product" />
                                            @*class="elevate__zoom" data-zoom-image="uploads/pr-large2.jpg" id="elevate__zoom" title="product-2">*@
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product__view__image col-md-6 col-sm-6 col-xs-12">

                            <div class="name" style="font-size:35px">@Html.DisplayFor(model => model.tenLoaiDV)</div>
                            <div class="product__view__des" style="font-size:20px;color:black">
                                <label>tên loại dịch vụ:</label>
                                <span class="name">
                                    @Html.DisplayFor(model => model.tenLoaiDV)
                                </span>
                            </div>
                            <div class="product__view__des" style="        font-size: 20px;
        color: black
">
                                <label>Số lượng Ngày thực hiện</label>
                                <span class="name">
                                    @Html.DisplayFor(model => model.NgayTH)
                                </span>
                            </div>

                            <div class="product__view__des" style="        font-size: 20px;
        color: black
">
                                <label>
                                    Giá:
                                </label>

                                <span class="name">
                                    @Html.DisplayFor(model => model.Gia)
                                </span>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="row">
                                        <div class="col-2">
                                            @*<div class="form-control" style="width:60px; height:35px; background-color:blue">
                                                <span class="name">
                                                    @Html.ActionLink("Edit", "Edit", new { id = Model.MaSP })
                                                </span>*@
                                            <a href="@Url.Action("Edit", "ServiceType", new { id = Model.idLoaiDV })" class="btn btn-primary">Edit</a>
                                        </div>
                                        <div class="col-2">
                                            <a href="#" onclick="XoaDichVu('@Model.idLoaiDV')" class="btn btn-primary">Delete</a>
                                        </div>
                                        <div class="col-2">
                                            <a href="@Url.Action("Index", "ServiceType") " class="btn btn-primary">Back</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
        function XoaDichVu(id) {
            if (confirm("Bạn muốn xóa dịch vụ này?") == true) {
                $.post("/Areas/Admin/Service/Delete", { "id": id }, function (data) {
                    location.href = "/Service";
                })
            } else {

            }
        }
</script>

Website QlySpa/QlySpa/QlySpa/Areas/Admin/Views/ServiceType/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model QlySpa.Models.EF.LoaiDichVu



@*@using (Html.BeginForm())
    <form action="Edit" method="post" role="form" enctype="multipart/form-data">
    <div class="form-horizontal">
    {
        @Html.AntiForgeryToken()}*@
@*<form action="Edit" method="post" role="form" enctype="multipart/form-data">*@
<form action="Edit" method="post" role="form" enctype="multipart/form-data">
    <div class="form-horizontal">
        <input type="hidden" name="id" value="@ViewBag.id" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*  @Html.HiddenFor(model => model.MaSP)*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaSP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="sec sec__shopcart">
            <div class="container">
                <div class="sec__shopcart__info col-md-12 col-xs-12 col-sm-12">
                    <div class="box-user__info panel">
                        <h2><u>Chỉnh sửa thông tin loại dịch vụ</u></h2>
                        <div class="content">
                            <div class="row">
                                <div class="col-md-6 col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <div class="label">Tên Loai dich vu</div>

                                        <!--@Html.LabelFor(model => model.tenLoaiDV, htmlAttributes: new { @class = "control-label col-md-2" })-->
                                        <!--<div class="col-md-6">-->
                                        @Html.EditorFor(model => model.tenLoaiDV, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.tenLoaiDV, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6 col-xs-12 col-sm-6">
                                    <div class="form-group">
                                        <div class="label">Hình ảnh</div>
                                        <input type="file" id="photo" name="photo" onchange="previewFile(this)">
                                        @*<p class="help-block">Chọn ảnh của sản phẩm</p>*@
                                        <img id="previewImg" src="/Areas/Admin/Content/images/@Model.Anh" style="width: 70px; height: 70px;" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <div class="label">Số đăng ký</div>
                                    @Html.EditorFor(model => model.NgayTH, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NgayTH, "", new { @class = "text-danger" })
                                </div>
                            </div>
                           

                        </div>
                        <div class="row">
                            <div class="col-md-6 col-xs-12 col-sm-6">
                                <div class="form-group">
                                    <div class="label">Gia</div>
                                    @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control",  @Value = @ViewBag.Gia } })
                                    @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                                </div>
                            </div>
                           
                        </div>
                        <div class="row">
                            <div class="col-md-2 col-xs-12 col-sm-2">
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-2 col-xs-12 col-sm-2">
                                <div class="col-2">
                                    <a href="@Url.Action("Index", "ServiceType") " class="btn btn-primary">Back</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<style>
    body {
    }

    h2 {
        color: royalblue;
        font-family: Arial;
        font-weight: bold;
    }
</style>
@* } *@

Website QlySpa/QlySpa/QlySpa/Areas/Admin/Views/ServiceType/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc

@model PagedList.IPagedList<QlySpa.Models.EF.LoaiDichVu>

<h2>Quản Lý Dịch Vụ</h2>

<div class="sec list-product">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 col-right">
                <h2>Sản phẩm</h2>
                <div class="form-search">
                    @using (Html.BeginForm("Index", "ServiceType", FormMethod.Get, new { }))
                    {

                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-3">
                                        <div class="">
                                            <input type="text" class="form-control" name="NgayTH" placeholder="Nhập ngày đăng ký" value="@ViewBag.NgayTH">
                                        </div>
                                    </div>
                                    <div class="col-2">
                                        <div class="btn-search">
                                            <button type="submit" class="btn btn-default btn-pro" title="Search" style="background-color:lightgreen;width:70px; height:38px ">
                                                <i class="fa fa-search"></i>
                                            </button>
                                            <a href="~/Admin/ServiceType" class="btn btn-default btn-pro" title="Reload" style=" background-color: lightgreen;
                                                        width: 70px;
                                                        height: 38px">
                                                <i class="fas fa-sync-alt"></i>

                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <p>
                    @Html.ActionLink("Thêm mới một sản phẩm ", "Create")
                </p>
                @*<table class="table">
                    <tr>
                        <th>
                            Tên sản phẩm
                        </th>
                        <th>
                            Hình ảnh
                        </th>
                        <th>
                            Số đăng ký
                        </th>
                        <th>
                            Hạn sử dụng
                        </th>
                        <th>
                            Ngày đăng ký
                        </th>
                        <th>
                            Quy cách
                        </th>
                        <th>Tác vụ</th>
                    </tr>*@

                <div class="box-ct">
                    <div class="list-ct">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                <div class="col-md-3 col-sm-3 col-xs-6" style="border: 1px solid #dee2e6;">
                                    <div class="product__item">
                                        <div class="w">
                                            <div class="product__image">
                                                <a href="@Url.Action("Details", "ServiceType", new { id = item.idLoaiDV })" class="product__link"><img src="/Areas/Admin/Content/images/@item.Anh" style="width: 250px; height: 250px;" alt="name your product"></a>
                                            </div>
                                            <h3 class="product__name" style="font-size:21px"><a href="@Url.Action("Details", "ServiceType", new { id = item.idLoaiDV })">@item.tenLoaiDV</a></h3>
                                            @*<div class="product__">@item.ProStatus</div>*@

                                        </div>


                                    </div>

                                </div>
                            }
                        </div>
                    </div>
                </div>
                @if (ViewBag.HienThi != "1")
                {
                    <ul class="pagination">
                        Page @(Model.PageCount<Model.PageNumber? 0: Model.PageNumber) of @Model.PageCount
                        @Html.PagedListPager(Model, pageNum => Url.Action("Index", new { pageNum }))
                    </ul>
                }
            </div>
        </div>
    </div>
</div>
<style>
    body {
    }

    h2 {
        color: royalblue;
        font-family: Arial;
        font-weight: bold;
    }

    img {
        width: 12px;
        height: 12px;
        margin-left: 3px;
        margin-right: 3px;
    }

    .table {
        width: 100%;
    }

        .table th,
        .table td {
            padding: 0.2rem;
            vertical-align: top;
            border: 1px solid #dee2e6;
            display: table-cell;
            text-align: center;
            background-color: aliceblue;
            font-family: arial, sans-serif;
        }

        .table th {
            background-color: mediumturquoise;
            color: aliceblue;
        }

    .pagination {
        margin-top: 10px;
    }

        .pagination a {
            color: black;
            float: left;
            padding: 12px 18px;
            text-decoration: none;
        }

        .pagination li {
            background-color: #e9e9e9;
            border-radius: 5px;
            margin-left: 4px;
        }

    l

    .pagination .active {
        background-color: dodgerblue;
        color: white;
        border-radius: 5px;
    }

    .pagination a:hover:not(.active) {
        background-color: #ddd;
        border-radius: 5px;
    }
</style>